---

- name: "create dir {{ celery_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
  with_items: "{{ celery_dir }}"
  become: yes

- name: copy celery service config
  copy:
    src: etc/
    dest: /etc/
    owner: root
    group: root
  become: yes

- name: load and start celery service
  systemd:
    daemon_reload: yes
    name: celery
    state: started
  become: yes

