- debug: 
    msg: "{{ provision }}"

- name: Ensure all the debian packages are installed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-virtualenv
    - python3-pip

- name: Add the user collector
  user:
    name: collector
    groups: collector

- name: Creates /srv/bin directory
  file:
    path: /srv/bin
    owner: collector
    group: collector
    mode: 0775
    state: directory

- name: Download wordlists
  git:
    accept_hostkey: yes
    clone: yes
    dest: /srv/wordlists
    repo: git@gitlab.com:opulence/wordlists.git

- name: add /srv/bin to path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?/srv/bin).*?)(["]*)$'
    line="PATH=\1\2:/srv/bin\3"

- name: Include all tasks
  include: "{{ item }}"
  with_items: "{{ provision }}"

- name: Ensure all the directories are created with the right permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: collector
    group: collector
    recurse: yes
  with_items:
    - /srv/bin
    - /srv/scripts
    - /srv/wordlists