---
- block:
  - name: 'nmap : Install nmap'
    become: true
    apt:
      name: nmap
      update_cache: yes
      state: latest

  - name: 'nmap : Set capabilities'
    capabilities:
      path: /usr/bin/nmap
      capability: cap_net_raw,cap_net_admin,cap_net_bind_service+eip
      state: present

  - name: 'nmap : NMAP_PRIVILEGED'
    lineinfile:
      dest: "/etc/environment"
      state: present
      regexp: "^NMAP_PRIVILEGED"
      line: "NMAP_PRIVILEGED=''"
  tags:
    - nmap