---
- block:

  - name: 'recon-ng : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /srv/scripts/recon-ng
      force: yes
      repo: https://github.com/lanmaster53/recon-ng.git

  - name: 'recon-ng : clone modules repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /home/collector/.recon-ng
      force: yes
      repo: https://github.com/lanmaster53/recon-ng-marketplace.git
    become: yes
    become_user: collector

  - name: 'recon-ng : remove existing venv'
    file:
      path: /srv/scripts/recon-ng/env
      state: absent

  - name: 'recon-ng : install requirements'
    pip:
      requirements: /srv/scripts/recon-ng/REQUIREMENTS
      virtualenv: /srv/scripts/recon-ng/.venv
      virtualenv_python: python3

  - name: 'recon-ng : install launcher'
    file:
      src: /srv/scripts/recon-ng/env/bin/recon-cli
      dest: /srv/bin/recon-ng
      owner: collector
      group: collector
      state: link

  tags:
    - recon-ng
