---
user: vagrant
group: vagrant

packages:
  - docker.io
  - python3.7
  - python3-venv
  - python3-pip

ssh_authorized_keys:
  - henry
  - louis
  - augustin

target_dir: "/opt/opullence"

packages_pip: [setuptools, pip]

celery_dir: ["/var/log/celery", "/var/run/celery"]


provision:
  - a
  - b
  - c