---

- name: install system packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  become: yes

- name: Copy ssh key
  authorized_key:
    key: "{{ lookup('file', ssh_pub_key_dir + '/' + item + '.pub') }}"
    user: vagrant
  with_items: "{{ ssh_authorized_keys }}"