version: '2'

services:
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/opt/redis/data'
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'


volumes:
  redis_data:
    driver: local